question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "There are 6 legendary cards in 'Clash Royale'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Pokemon Sun and Moon, a male Salandit can evolve to a Salazzle.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "'Half-Life 2' runs on the Source Engine.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Sonic the Hedgehog universe, Tails' real name is Miles Prower.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "'Resident Evil 7' is the first first-person Resident Evil game.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In the 'Half-Life' series, 'H.E.V' stands for 'Hazardous Evasiveness Vest'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Tetris is the #1 best-selling video game of all-time.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series' history.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
